apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-platform-deployment-backend
  namespace: app
  labels:
    app.kubernetes.io/name: gitops-platform-backend
    app.kubernetes.io/instance: gitops-platform-backend-production
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    team: a-team
    env: production
spec:
  replicas: {{ .Values.replicaCountBackend }}
  minReadySeconds: 30
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxUnavailable: 20%
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitops-platform-backend
      app.kubernetes.io/instance: gitops-platform-backend-production
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      team: a-team
      env: production
  template:
    metadata:
      annotations:
        # Force deployment replicas rollout on each change.
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: gitops-platform-backend
        app.kubernetes.io/instance: gitops-platform-backend-production
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        team: a-team
        env: production
    spec:
      containers:
        - name: app-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          envFrom:
            - configMapRef:
                name: gitops-platform-config
            - secretRef:
                name: gitops-platform-secrets
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 5
