apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: app
  labels:
    app.kubernetes.io/name: backend-service
spec:
  selector:
    app.kubernetes.io/name: gitops-platform-backend
    app.kubernetes.io/instance: gitops-platform-backend-production
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
