apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-platform-config
data:
  NODE_ENV: "development"
  PORT: "4000"
  JWT_EXPIRES_IN: "30d"
  CORS_ORIGIN: "gitops-platform-deployment-frontend:5173"
  BASE_API_URL: "/api"
