apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: gitops-platform-frontend
    app.kubernetes.io/instance: gitops-platform-frontend-production
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
