apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gitops-platform-hpa
  namespace: app
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gitops-platform-deployment-frontend
  targetCPUUtilizationPercentage: 80
