replicaCountFrontend: 2
replicaCountBackend: 2

ingress:
  enabled: true
  className: alb
  hosts:
    - host: ""

frontend:
  image:
    repository: "ecr repo" # Editable
    tag: "dev"
  resources:
    requests:
      memory: 128Mi
      cpu: 64m
    limits:
      memory: 256Mi
      cpu: 128m

backend:
  image:
    repository: "ecr repo" # Editable
    tag: "dev"
  resources:
    requests:
      memory: 128Mi
      cpu: 64m
    limits:
      memory: 256Mi
      cpu: 128m
